### ISSUE TITLE
Write alerter functionality

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#13]
Alerter should support different kinds of alerting mechanisms (slack, pagerduty, email to start?).

Spawn an alert channel; checks write to the alert channel when they want to send out an alert; alerter listens on alert channel for incoming messages and spins up alerter workers to handle the message sending via whatever alerting method.

We *could* cache the entirety of the alerting config in mem to save on a bunch of `fetchAlertConfig()` calls to etcd. Not sure yet. Bonus points for this. Oh. If etcd ever goes away, so does the node's alerting abilities - so we should probably just cache it from the getgo - that way we can survive an etcd outage/restart without (too many) issues.

**Comment by dselans** [comment]
Reminder: checks reference thresholds (OK, WARNING, CRITICAL), each threshold is associated with an alert key entry.

YAML wise, this would look something like:

```yaml
WarningThreshold:
  Alerter: core-slack-all-hours
  FailCount: 2 # or some other key that the check requires (?)
CriticalThreshold:
  Alerter: core-pagerduty-all-hours
  FailCount: 5
```
